// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AmountInputController from "./amount_input_controller"
application.register("amount-input", AmountInputController)

import AssetToggleController from "./asset_toggle_controller"
application.register("asset-toggle", AssetToggleController)

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CardPaymentController from "./card_payment_controller"
application.register("card-payment", CardPaymentController)

import CategorySelectorController from "./category_selector_controller"
application.register("category-selector", CategorySelectorController)

import ConfirmController from "./confirm_controller"
application.register("confirm", ConfirmController)

import DatePickerController from "./date_picker_controller"
application.register("date-picker", DatePickerController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import IconPickerController from "./icon_picker_controller"
application.register("icon-picker", IconPickerController)

import InlineEditController from "./inline_edit_controller"
application.register("inline-edit", InlineEditController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import StatsChartController from "./stats_chart_controller"
application.register("stats-chart", StatsChartController)

import StatsFilterController from "./stats_filter_controller"
application.register("stats-filter", StatsFilterController)

import TagFormController from "./tag_form_controller"
application.register("tag-form", TagFormController)

import TagSelectorController from "./tag_selector_controller"
application.register("tag-selector", TagSelectorController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import TransactionFormController from "./transaction_form_controller"
application.register("transaction-form", TransactionFormController)

import TrendChartController from "./trend_chart_controller"
application.register("trend-chart", TrendChartController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)

import UnsavedChangesController from "./unsaved_changes_controller"
application.register("unsaved-changes", UnsavedChangesController)
