"""Add deleted_at to recurring_transactions

Revision ID: 48c2c2d3348f
Revises: fe552720537a
Create Date: 2025-10-25 10:23:46.722892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c2c2d3348f'
down_revision: Union[str, None] = 'fe552720537a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_transactions', 'deleted_at')
    # ### end Alembic commands ###
