"""Add asset_adjustments table

Revision ID: b4188df4a07e
Revises: 48c2c2d3348f
Create Date: 2025-11-30 05:52:05.415874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4188df4a07e'
down_revision: Union[str, None] = '48c2c2d3348f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INCOME_MISSING', 'EXPENSE_MISSING', name='adjustmenttype'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_adjustments_adjustment_date'), 'asset_adjustments', ['adjustment_date'], unique=False)
    op.create_index(op.f('ix_asset_adjustments_id'), 'asset_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_asset_adjustments_user_id'), 'asset_adjustments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_adjustments_user_id'), table_name='asset_adjustments')
    op.drop_index(op.f('ix_asset_adjustments_id'), table_name='asset_adjustments')
    op.drop_index(op.f('ix_asset_adjustments_adjustment_date'), table_name='asset_adjustments')
    op.drop_table('asset_adjustments')
    # ### end Alembic commands ###
