"""Change transaction date from DateTime to Date

Revision ID: cb060ef402e7
Revises: 9c453f423844
Create Date: 2025-10-18 08:13:30.216898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb060ef402e7'
down_revision: Union[str, None] = '9c453f423844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # TIMESTAMP를 DATE로 변환 (기존 데이터의 시간 정보 제거)
    op.alter_column('transactions', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='date::date')  # PostgreSQL 명시적 캐스팅
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
