"""add order field to categories

Revision ID: fe552720537a
Revises: cb060ef402e7
Create Date: 2025-10-19 03:52:35.872616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe552720537a'
down_revision: Union[str, None] = 'cb060ef402e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. 컬럼 추가 (nullable=True로 임시 생성)
    op.add_column('categories', sa.Column('order', sa.Integer(), nullable=True))

    # 2. 기존 데이터에 순서 부여
    op.execute("""
        WITH ordered_categories AS (
            SELECT id, row_number() OVER (PARTITION BY user_id ORDER BY created_at) - 1 AS new_order
            FROM categories
        )
        UPDATE categories
        SET "order" = ordered_categories.new_order
        FROM ordered_categories
        WHERE categories.id = ordered_categories.id
    """)

    # 3. NOT NULL 제약 조건 추가
    op.alter_column('categories', 'order', nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'order')
    # ### end Alembic commands ###
